package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * BillpaymentSupplier generated by hbm2java
 */
public class BillpaymentSupplier implements java.io.Serializable {

	private Integer supplierBillpaymentId;
	private MasterSupplier masterSupplier;
	private Integer supplierBillno;
	private Date supplierBilldt;
	private BigDecimal supplierBillpaymentAmt;
	private BigDecimal supplierOrgpaymentAmt;
	private Date supplierOrgpaymentdt;
	private String supplierOrgpaymentRef;
	private String supplierBillComments;
	private byte[] supplierBillImg;

	public BillpaymentSupplier() {
	}

	public BillpaymentSupplier(MasterSupplier masterSupplier) {
		this.masterSupplier = masterSupplier;
	}

	public BillpaymentSupplier(MasterSupplier masterSupplier,
			Integer supplierBillno, Date supplierBilldt,
			BigDecimal supplierBillpaymentAmt,
			BigDecimal supplierOrgpaymentAmt, Date supplierOrgpaymentdt,
			String supplierOrgpaymentRef, String supplierBillComments,
			byte[] supplierBillImg) {
		this.masterSupplier = masterSupplier;
		this.supplierBillno = supplierBillno;
		this.supplierBilldt = supplierBilldt;
		this.supplierBillpaymentAmt = supplierBillpaymentAmt;
		this.supplierOrgpaymentAmt = supplierOrgpaymentAmt;
		this.supplierOrgpaymentdt = supplierOrgpaymentdt;
		this.supplierOrgpaymentRef = supplierOrgpaymentRef;
		this.supplierBillComments = supplierBillComments;
		this.supplierBillImg = supplierBillImg;
	}

	public Integer getSupplierBillpaymentId() {
		return this.supplierBillpaymentId;
	}

	public void setSupplierBillpaymentId(Integer supplierBillpaymentId) {
		this.supplierBillpaymentId = supplierBillpaymentId;
	}

	public MasterSupplier getMasterSupplier() {
		return this.masterSupplier;
	}

	public void setMasterSupplier(MasterSupplier masterSupplier) {
		this.masterSupplier = masterSupplier;
	}

	public Integer getSupplierBillno() {
		return this.supplierBillno;
	}

	public void setSupplierBillno(Integer supplierBillno) {
		this.supplierBillno = supplierBillno;
	}

	public Date getSupplierBilldt() {
		return this.supplierBilldt;
	}

	public void setSupplierBilldt(Date supplierBilldt) {
		this.supplierBilldt = supplierBilldt;
	}

	public BigDecimal getSupplierBillpaymentAmt() {
		return this.supplierBillpaymentAmt;
	}

	public void setSupplierBillpaymentAmt(BigDecimal supplierBillpaymentAmt) {
		this.supplierBillpaymentAmt = supplierBillpaymentAmt;
	}

	public BigDecimal getSupplierOrgpaymentAmt() {
		return this.supplierOrgpaymentAmt;
	}

	public void setSupplierOrgpaymentAmt(BigDecimal supplierOrgpaymentAmt) {
		this.supplierOrgpaymentAmt = supplierOrgpaymentAmt;
	}

	public Date getSupplierOrgpaymentdt() {
		return this.supplierOrgpaymentdt;
	}

	public void setSupplierOrgpaymentdt(Date supplierOrgpaymentdt) {
		this.supplierOrgpaymentdt = supplierOrgpaymentdt;
	}

	public String getSupplierOrgpaymentRef() {
		return this.supplierOrgpaymentRef;
	}

	public void setSupplierOrgpaymentRef(String supplierOrgpaymentRef) {
		this.supplierOrgpaymentRef = supplierOrgpaymentRef;
	}

	public String getSupplierBillComments() {
		return this.supplierBillComments;
	}

	public void setSupplierBillComments(String supplierBillComments) {
		this.supplierBillComments = supplierBillComments;
	}

	public byte[] getSupplierBillImg() {
		return this.supplierBillImg;
	}

	public void setSupplierBillImg(byte[] supplierBillImg) {
		this.supplierBillImg = supplierBillImg;
	}

}
