package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * BillpaymentCustomer generated by hbm2java
 */
public class BillpaymentCustomer implements java.io.Serializable {

	private Integer customerBillpaymentId;
	private MasterCustomer masterCustomer;
	private ProdMob prodMob;
	private int customerBillno;
	private BigDecimal customerBillamount;
	private Date customerBilldt;
	private String customerBillpaymentref;
	private BigDecimal customerPaidamount;
	private Date customerPaiddt;
	private BigDecimal customerCreditamount;
	private Date customerCreditrcddate;

	public BillpaymentCustomer() {
	}

	public BillpaymentCustomer(MasterCustomer masterCustomer,
			int customerBillno, BigDecimal customerBillamount,
			Date customerBilldt) {
		this.masterCustomer = masterCustomer;
		this.customerBillno = customerBillno;
		this.customerBillamount = customerBillamount;
		this.customerBilldt = customerBilldt;
	}

	public BillpaymentCustomer(MasterCustomer masterCustomer, ProdMob prodMob,
			int customerBillno, BigDecimal customerBillamount,
			Date customerBilldt, String customerBillpaymentref,
			BigDecimal customerPaidamount, Date customerPaiddt,
			BigDecimal customerCreditamount, Date customerCreditrcddate) {
		this.masterCustomer = masterCustomer;
		this.prodMob = prodMob;
		this.customerBillno = customerBillno;
		this.customerBillamount = customerBillamount;
		this.customerBilldt = customerBilldt;
		this.customerBillpaymentref = customerBillpaymentref;
		this.customerPaidamount = customerPaidamount;
		this.customerPaiddt = customerPaiddt;
		this.customerCreditamount = customerCreditamount;
		this.customerCreditrcddate = customerCreditrcddate;
	}

	public Integer getCustomerBillpaymentId() {
		return this.customerBillpaymentId;
	}

	public void setCustomerBillpaymentId(Integer customerBillpaymentId) {
		this.customerBillpaymentId = customerBillpaymentId;
	}

	public MasterCustomer getMasterCustomer() {
		return this.masterCustomer;
	}

	public void setMasterCustomer(MasterCustomer masterCustomer) {
		this.masterCustomer = masterCustomer;
	}

	public ProdMob getProdMob() {
		return this.prodMob;
	}

	public void setProdMob(ProdMob prodMob) {
		this.prodMob = prodMob;
	}

	public int getCustomerBillno() {
		return this.customerBillno;
	}

	public void setCustomerBillno(int customerBillno) {
		this.customerBillno = customerBillno;
	}

	public BigDecimal getCustomerBillamount() {
		return this.customerBillamount;
	}

	public void setCustomerBillamount(BigDecimal customerBillamount) {
		this.customerBillamount = customerBillamount;
	}

	public Date getCustomerBilldt() {
		return this.customerBilldt;
	}

	public void setCustomerBilldt(Date customerBilldt) {
		this.customerBilldt = customerBilldt;
	}

	public String getCustomerBillpaymentref() {
		return this.customerBillpaymentref;
	}

	public void setCustomerBillpaymentref(String customerBillpaymentref) {
		this.customerBillpaymentref = customerBillpaymentref;
	}

	public BigDecimal getCustomerPaidamount() {
		return this.customerPaidamount;
	}

	public void setCustomerPaidamount(BigDecimal customerPaidamount) {
		this.customerPaidamount = customerPaidamount;
	}

	public Date getCustomerPaiddt() {
		return this.customerPaiddt;
	}

	public void setCustomerPaiddt(Date customerPaiddt) {
		this.customerPaiddt = customerPaiddt;
	}

	public BigDecimal getCustomerCreditamount() {
		return this.customerCreditamount;
	}

	public void setCustomerCreditamount(BigDecimal customerCreditamount) {
		this.customerCreditamount = customerCreditamount;
	}

	public Date getCustomerCreditrcddate() {
		return this.customerCreditrcddate;
	}

	public void setCustomerCreditrcddate(Date customerCreditrcddate) {
		this.customerCreditrcddate = customerCreditrcddate;
	}

}
