package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Expense generated by hbm2java
 */
public class Expense implements java.io.Serializable {

	private Integer expenseId;
	private String expTowhompaid;
	private String expPurpose;
	private BigDecimal expAmount;
	private Date expPaiddt;
	private String expComments;

	public Expense() {
	}

	public Expense(String expTowhompaid, String expPurpose,
			BigDecimal expAmount, Date expPaiddt) {
		this.expTowhompaid = expTowhompaid;
		this.expPurpose = expPurpose;
		this.expAmount = expAmount;
		this.expPaiddt = expPaiddt;
	}

	public Expense(String expTowhompaid, String expPurpose,
			BigDecimal expAmount, Date expPaiddt, String expComments) {
		this.expTowhompaid = expTowhompaid;
		this.expPurpose = expPurpose;
		this.expAmount = expAmount;
		this.expPaiddt = expPaiddt;
		this.expComments = expComments;
	}

	public Integer getExpenseId() {
		return this.expenseId;
	}

	public void setExpenseId(Integer expenseId) {
		this.expenseId = expenseId;
	}

	public String getExpTowhompaid() {
		return this.expTowhompaid;
	}

	public void setExpTowhompaid(String expTowhompaid) {
		this.expTowhompaid = expTowhompaid;
	}

	public String getExpPurpose() {
		return this.expPurpose;
	}

	public void setExpPurpose(String expPurpose) {
		this.expPurpose = expPurpose;
	}

	public BigDecimal getExpAmount() {
		return this.expAmount;
	}

	public void setExpAmount(BigDecimal expAmount) {
		this.expAmount = expAmount;
	}

	public Date getExpPaiddt() {
		return this.expPaiddt;
	}

	public void setExpPaiddt(Date expPaiddt) {
		this.expPaiddt = expPaiddt;
	}

	public String getExpComments() {
		return this.expComments;
	}

	public void setExpComments(String expComments) {
		this.expComments = expComments;
	}

}
