package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterUsrSecqns generated by hbm2java
 */
public class MasterUsrSecqns implements java.io.Serializable {

	private Integer masterUsrSecqnsId;
	private String masterUsrSecqnDesc;
	private Set users = new HashSet(0);

	public MasterUsrSecqns() {
	}

	public MasterUsrSecqns(String masterUsrSecqnDesc) {
		this.masterUsrSecqnDesc = masterUsrSecqnDesc;
	}

	public MasterUsrSecqns(String masterUsrSecqnDesc, Set users) {
		this.masterUsrSecqnDesc = masterUsrSecqnDesc;
		this.users = users;
	}

	public Integer getMasterUsrSecqnsId() {
		return this.masterUsrSecqnsId;
	}

	public void setMasterUsrSecqnsId(Integer masterUsrSecqnsId) {
		this.masterUsrSecqnsId = masterUsrSecqnsId;
	}

	public String getMasterUsrSecqnDesc() {
		return this.masterUsrSecqnDesc;
	}

	public void setMasterUsrSecqnDesc(String masterUsrSecqnDesc) {
		this.masterUsrSecqnDesc = masterUsrSecqnDesc;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
