package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterCustomer generated by hbm2java
 */
public class MasterCustomer implements java.io.Serializable {

	private Integer masterCustomerid;
	private MasterCustType masterCustType;
	private MasterCustRemdton masterCustRemdton;
	private String masterCustomername;
	private String masterCustomermob;
	private String masterCustomeremail;
	private String masterCustomeraddress;
	private String masterCustomerAddfldChr;
	private String masterCustomerAddfldChr2;
	private Set billpaymentCustomers = new HashSet(0);

	public MasterCustomer() {
	}

	public MasterCustomer(MasterCustRemdton masterCustRemdton,
			String masterCustomername, String masterCustomermob) {
		this.masterCustRemdton = masterCustRemdton;
		this.masterCustomername = masterCustomername;
		this.masterCustomermob = masterCustomermob;
	}

	public MasterCustomer(MasterCustType masterCustType,
			MasterCustRemdton masterCustRemdton, String masterCustomername,
			String masterCustomermob, String masterCustomeremail,
			String masterCustomeraddress, String masterCustomerAddfldChr,
			String masterCustomerAddfldChr2, Set billpaymentCustomers) {
		this.masterCustType = masterCustType;
		this.masterCustRemdton = masterCustRemdton;
		this.masterCustomername = masterCustomername;
		this.masterCustomermob = masterCustomermob;
		this.masterCustomeremail = masterCustomeremail;
		this.masterCustomeraddress = masterCustomeraddress;
		this.masterCustomerAddfldChr = masterCustomerAddfldChr;
		this.masterCustomerAddfldChr2 = masterCustomerAddfldChr2;
		this.billpaymentCustomers = billpaymentCustomers;
	}

	public Integer getMasterCustomerid() {
		return this.masterCustomerid;
	}

	public void setMasterCustomerid(Integer masterCustomerid) {
		this.masterCustomerid = masterCustomerid;
	}

	public MasterCustType getMasterCustType() {
		return this.masterCustType;
	}

	public void setMasterCustType(MasterCustType masterCustType) {
		this.masterCustType = masterCustType;
	}

	public MasterCustRemdton getMasterCustRemdton() {
		return this.masterCustRemdton;
	}

	public void setMasterCustRemdton(MasterCustRemdton masterCustRemdton) {
		this.masterCustRemdton = masterCustRemdton;
	}

	public String getMasterCustomername() {
		return this.masterCustomername;
	}

	public void setMasterCustomername(String masterCustomername) {
		this.masterCustomername = masterCustomername;
	}

	public String getMasterCustomermob() {
		return this.masterCustomermob;
	}

	public void setMasterCustomermob(String masterCustomermob) {
		this.masterCustomermob = masterCustomermob;
	}

	public String getMasterCustomeremail() {
		return this.masterCustomeremail;
	}

	public void setMasterCustomeremail(String masterCustomeremail) {
		this.masterCustomeremail = masterCustomeremail;
	}

	public String getMasterCustomeraddress() {
		return this.masterCustomeraddress;
	}

	public void setMasterCustomeraddress(String masterCustomeraddress) {
		this.masterCustomeraddress = masterCustomeraddress;
	}

	public String getMasterCustomerAddfldChr() {
		return this.masterCustomerAddfldChr;
	}

	public void setMasterCustomerAddfldChr(String masterCustomerAddfldChr) {
		this.masterCustomerAddfldChr = masterCustomerAddfldChr;
	}

	public String getMasterCustomerAddfldChr2() {
		return this.masterCustomerAddfldChr2;
	}

	public void setMasterCustomerAddfldChr2(String masterCustomerAddfldChr2) {
		this.masterCustomerAddfldChr2 = masterCustomerAddfldChr2;
	}

	public Set getBillpaymentCustomers() {
		return this.billpaymentCustomers;
	}

	public void setBillpaymentCustomers(Set billpaymentCustomers) {
		this.billpaymentCustomers = billpaymentCustomers;
	}

}
