package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterCustType generated by hbm2java
 */
public class MasterCustType implements java.io.Serializable {

	private Integer masterCustTypeId;
	private MasterGenStatus masterGenStatus;
	private String masterCustTypeDesc;
	private Set masterCustomers = new HashSet(0);

	public MasterCustType() {
	}

	public MasterCustType(MasterGenStatus masterGenStatus,
			String masterCustTypeDesc) {
		this.masterGenStatus = masterGenStatus;
		this.masterCustTypeDesc = masterCustTypeDesc;
	}

	public MasterCustType(MasterGenStatus masterGenStatus,
			String masterCustTypeDesc, Set masterCustomers) {
		this.masterGenStatus = masterGenStatus;
		this.masterCustTypeDesc = masterCustTypeDesc;
		this.masterCustomers = masterCustomers;
	}

	public Integer getMasterCustTypeId() {
		return this.masterCustTypeId;
	}

	public void setMasterCustTypeId(Integer masterCustTypeId) {
		this.masterCustTypeId = masterCustTypeId;
	}

	public MasterGenStatus getMasterGenStatus() {
		return this.masterGenStatus;
	}

	public void setMasterGenStatus(MasterGenStatus masterGenStatus) {
		this.masterGenStatus = masterGenStatus;
	}

	public String getMasterCustTypeDesc() {
		return this.masterCustTypeDesc;
	}

	public void setMasterCustTypeDesc(String masterCustTypeDesc) {
		this.masterCustTypeDesc = masterCustTypeDesc;
	}

	public Set getMasterCustomers() {
		return this.masterCustomers;
	}

	public void setMasterCustomers(Set masterCustomers) {
		this.masterCustomers = masterCustomers;
	}

}
