package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterProdStatus generated by hbm2java
 */
public class MasterProdStatus implements java.io.Serializable {

	private Integer masterProdStatusId;
	private String masterProdStatusDesc;
	private String masterProdStatusAddfldChr1;
	private String masterProdStatusAddfldChr2;
	private Set prodMobs = new HashSet(0);

	public MasterProdStatus() {
	}

	public MasterProdStatus(String masterProdStatusDesc) {
		this.masterProdStatusDesc = masterProdStatusDesc;
	}

	public MasterProdStatus(String masterProdStatusDesc,
			String masterProdStatusAddfldChr1,
			String masterProdStatusAddfldChr2, Set prodMobs) {
		this.masterProdStatusDesc = masterProdStatusDesc;
		this.masterProdStatusAddfldChr1 = masterProdStatusAddfldChr1;
		this.masterProdStatusAddfldChr2 = masterProdStatusAddfldChr2;
		this.prodMobs = prodMobs;
	}

	public Integer getMasterProdStatusId() {
		return this.masterProdStatusId;
	}

	public void setMasterProdStatusId(Integer masterProdStatusId) {
		this.masterProdStatusId = masterProdStatusId;
	}

	public String getMasterProdStatusDesc() {
		return this.masterProdStatusDesc;
	}

	public void setMasterProdStatusDesc(String masterProdStatusDesc) {
		this.masterProdStatusDesc = masterProdStatusDesc;
	}

	public String getMasterProdStatusAddfldChr1() {
		return this.masterProdStatusAddfldChr1;
	}

	public void setMasterProdStatusAddfldChr1(String masterProdStatusAddfldChr1) {
		this.masterProdStatusAddfldChr1 = masterProdStatusAddfldChr1;
	}

	public String getMasterProdStatusAddfldChr2() {
		return this.masterProdStatusAddfldChr2;
	}

	public void setMasterProdStatusAddfldChr2(String masterProdStatusAddfldChr2) {
		this.masterProdStatusAddfldChr2 = masterProdStatusAddfldChr2;
	}

	public Set getProdMobs() {
		return this.prodMobs;
	}

	public void setProdMobs(Set prodMobs) {
		this.prodMobs = prodMobs;
	}

}
