package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterProdCategory generated by hbm2java
 */
public class MasterProdCategory implements java.io.Serializable {

	private Integer masterProdCategoryId;
	private String masterProdCategoryDesc;
	private String masterProdCategoryAddfldChr1;
	private String masterProdCategoryAddfldChr2;
	private Set prodOtherses = new HashSet(0);

	public MasterProdCategory() {
	}

	public MasterProdCategory(String masterProdCategoryDesc) {
		this.masterProdCategoryDesc = masterProdCategoryDesc;
	}

	public MasterProdCategory(String masterProdCategoryDesc,
			String masterProdCategoryAddfldChr1,
			String masterProdCategoryAddfldChr2, Set prodOtherses) {
		this.masterProdCategoryDesc = masterProdCategoryDesc;
		this.masterProdCategoryAddfldChr1 = masterProdCategoryAddfldChr1;
		this.masterProdCategoryAddfldChr2 = masterProdCategoryAddfldChr2;
		this.prodOtherses = prodOtherses;
	}

	public Integer getMasterProdCategoryId() {
		return this.masterProdCategoryId;
	}

	public void setMasterProdCategoryId(Integer masterProdCategoryId) {
		this.masterProdCategoryId = masterProdCategoryId;
	}

	public String getMasterProdCategoryDesc() {
		return this.masterProdCategoryDesc;
	}

	public void setMasterProdCategoryDesc(String masterProdCategoryDesc) {
		this.masterProdCategoryDesc = masterProdCategoryDesc;
	}

	public String getMasterProdCategoryAddfldChr1() {
		return this.masterProdCategoryAddfldChr1;
	}

	public void setMasterProdCategoryAddfldChr1(
			String masterProdCategoryAddfldChr1) {
		this.masterProdCategoryAddfldChr1 = masterProdCategoryAddfldChr1;
	}

	public String getMasterProdCategoryAddfldChr2() {
		return this.masterProdCategoryAddfldChr2;
	}

	public void setMasterProdCategoryAddfldChr2(
			String masterProdCategoryAddfldChr2) {
		this.masterProdCategoryAddfldChr2 = masterProdCategoryAddfldChr2;
	}

	public Set getProdOtherses() {
		return this.prodOtherses;
	}

	public void setProdOtherses(Set prodOtherses) {
		this.prodOtherses = prodOtherses;
	}

}
