package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterGenStatus generated by hbm2java
 */
public class MasterGenStatus implements java.io.Serializable {

	private int genStatusId;
	private String masterGenStatusDesc;
	private String masterGenStatusComments;
	private Set masterSuppliers = new HashSet(0);
	private Set masterMobBrands = new HashSet(0);
	private Set masterCompBranchs = new HashSet(0);
	private Set users = new HashSet(0);
	private Set masterCustTypes = new HashSet(0);
	private Set masterCustRemdtons = new HashSet(0);
	private Set masterRoles = new HashSet(0);
	private Set masterCompanies = new HashSet(0);

	public MasterGenStatus() {
	}

	public MasterGenStatus(int genStatusId, String masterGenStatusDesc) {
		this.genStatusId = genStatusId;
		this.masterGenStatusDesc = masterGenStatusDesc;
	}

	public MasterGenStatus(int genStatusId, String masterGenStatusDesc,
			String masterGenStatusComments, Set masterSuppliers,
			Set masterMobBrands, Set masterCompBranchs, Set users,
			Set masterCustTypes, Set masterCustRemdtons, Set masterRoles,
			Set masterCompanies) {
		this.genStatusId = genStatusId;
		this.masterGenStatusDesc = masterGenStatusDesc;
		this.masterGenStatusComments = masterGenStatusComments;
		this.masterSuppliers = masterSuppliers;
		this.masterMobBrands = masterMobBrands;
		this.masterCompBranchs = masterCompBranchs;
		this.users = users;
		this.masterCustTypes = masterCustTypes;
		this.masterCustRemdtons = masterCustRemdtons;
		this.masterRoles = masterRoles;
		this.masterCompanies = masterCompanies;
	}

	public int getGenStatusId() {
		return this.genStatusId;
	}

	public void setGenStatusId(int genStatusId) {
		this.genStatusId = genStatusId;
	}

	public String getMasterGenStatusDesc() {
		return this.masterGenStatusDesc;
	}

	public void setMasterGenStatusDesc(String masterGenStatusDesc) {
		this.masterGenStatusDesc = masterGenStatusDesc;
	}

	public String getMasterGenStatusComments() {
		return this.masterGenStatusComments;
	}

	public void setMasterGenStatusComments(String masterGenStatusComments) {
		this.masterGenStatusComments = masterGenStatusComments;
	}

	public Set getMasterSuppliers() {
		return this.masterSuppliers;
	}

	public void setMasterSuppliers(Set masterSuppliers) {
		this.masterSuppliers = masterSuppliers;
	}

	public Set getMasterMobBrands() {
		return this.masterMobBrands;
	}

	public void setMasterMobBrands(Set masterMobBrands) {
		this.masterMobBrands = masterMobBrands;
	}

	public Set getMasterCompBranchs() {
		return this.masterCompBranchs;
	}

	public void setMasterCompBranchs(Set masterCompBranchs) {
		this.masterCompBranchs = masterCompBranchs;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getMasterCustTypes() {
		return this.masterCustTypes;
	}

	public void setMasterCustTypes(Set masterCustTypes) {
		this.masterCustTypes = masterCustTypes;
	}

	public Set getMasterCustRemdtons() {
		return this.masterCustRemdtons;
	}

	public void setMasterCustRemdtons(Set masterCustRemdtons) {
		this.masterCustRemdtons = masterCustRemdtons;
	}

	public Set getMasterRoles() {
		return this.masterRoles;
	}

	public void setMasterRoles(Set masterRoles) {
		this.masterRoles = masterRoles;
	}

	public Set getMasterCompanies() {
		return this.masterCompanies;
	}

	public void setMasterCompanies(Set masterCompanies) {
		this.masterCompanies = masterCompanies;
	}

}
