package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterSupplier generated by hbm2java
 */
public class MasterSupplier implements java.io.Serializable {

	private Integer masterSupplierId;
	private MasterGenStatus masterGenStatus;
	private MasterMobBrand masterMobBrand;
	private String masterSupplierName;
	private String masterSupplierAddress;
	private String masterSupplierTax;
	private String masterSupplierPhmob;
	private String masterSupplierPhll;
	private String masterSupplierEmail;
	private String masterSupplierWebsite;
	private String masterSupplierFeedback;
	private String masterSupplierAddfldChar1;
	private String masterSupplierAddfldChar2;
	private String masterSupplierAddfldChar3;
	private Set prodMobs = new HashSet(0);
	private Set billpaymentSuppliers = new HashSet(0);

	public MasterSupplier() {
	}

	public MasterSupplier(MasterGenStatus masterGenStatus,
			MasterMobBrand masterMobBrand, String masterSupplierName,
			String masterSupplierAddress, String masterSupplierTax,
			String masterSupplierPhmob, String masterSupplierPhll,
			String masterSupplierEmail) {
		this.masterGenStatus = masterGenStatus;
		this.masterMobBrand = masterMobBrand;
		this.masterSupplierName = masterSupplierName;
		this.masterSupplierAddress = masterSupplierAddress;
		this.masterSupplierTax = masterSupplierTax;
		this.masterSupplierPhmob = masterSupplierPhmob;
		this.masterSupplierPhll = masterSupplierPhll;
		this.masterSupplierEmail = masterSupplierEmail;
	}

	public MasterSupplier(MasterGenStatus masterGenStatus,
			MasterMobBrand masterMobBrand, String masterSupplierName,
			String masterSupplierAddress, String masterSupplierTax,
			String masterSupplierPhmob, String masterSupplierPhll,
			String masterSupplierEmail, String masterSupplierWebsite,
			String masterSupplierFeedback, String masterSupplierAddfldChar1,
			String masterSupplierAddfldChar2, String masterSupplierAddfldChar3,
			Set prodMobs, Set billpaymentSuppliers) {
		this.masterGenStatus = masterGenStatus;
		this.masterMobBrand = masterMobBrand;
		this.masterSupplierName = masterSupplierName;
		this.masterSupplierAddress = masterSupplierAddress;
		this.masterSupplierTax = masterSupplierTax;
		this.masterSupplierPhmob = masterSupplierPhmob;
		this.masterSupplierPhll = masterSupplierPhll;
		this.masterSupplierEmail = masterSupplierEmail;
		this.masterSupplierWebsite = masterSupplierWebsite;
		this.masterSupplierFeedback = masterSupplierFeedback;
		this.masterSupplierAddfldChar1 = masterSupplierAddfldChar1;
		this.masterSupplierAddfldChar2 = masterSupplierAddfldChar2;
		this.masterSupplierAddfldChar3 = masterSupplierAddfldChar3;
		this.prodMobs = prodMobs;
		this.billpaymentSuppliers = billpaymentSuppliers;
	}

	public Integer getMasterSupplierId() {
		return this.masterSupplierId;
	}

	public void setMasterSupplierId(Integer masterSupplierId) {
		this.masterSupplierId = masterSupplierId;
	}

	public MasterGenStatus getMasterGenStatus() {
		return this.masterGenStatus;
	}

	public void setMasterGenStatus(MasterGenStatus masterGenStatus) {
		this.masterGenStatus = masterGenStatus;
	}

	public MasterMobBrand getMasterMobBrand() {
		return this.masterMobBrand;
	}

	public void setMasterMobBrand(MasterMobBrand masterMobBrand) {
		this.masterMobBrand = masterMobBrand;
	}

	public String getMasterSupplierName() {
		return this.masterSupplierName;
	}

	public void setMasterSupplierName(String masterSupplierName) {
		this.masterSupplierName = masterSupplierName;
	}

	public String getMasterSupplierAddress() {
		return this.masterSupplierAddress;
	}

	public void setMasterSupplierAddress(String masterSupplierAddress) {
		this.masterSupplierAddress = masterSupplierAddress;
	}

	public String getMasterSupplierTax() {
		return this.masterSupplierTax;
	}

	public void setMasterSupplierTax(String masterSupplierTax) {
		this.masterSupplierTax = masterSupplierTax;
	}

	public String getMasterSupplierPhmob() {
		return this.masterSupplierPhmob;
	}

	public void setMasterSupplierPhmob(String masterSupplierPhmob) {
		this.masterSupplierPhmob = masterSupplierPhmob;
	}

	public String getMasterSupplierPhll() {
		return this.masterSupplierPhll;
	}

	public void setMasterSupplierPhll(String masterSupplierPhll) {
		this.masterSupplierPhll = masterSupplierPhll;
	}

	public String getMasterSupplierEmail() {
		return this.masterSupplierEmail;
	}

	public void setMasterSupplierEmail(String masterSupplierEmail) {
		this.masterSupplierEmail = masterSupplierEmail;
	}

	public String getMasterSupplierWebsite() {
		return this.masterSupplierWebsite;
	}

	public void setMasterSupplierWebsite(String masterSupplierWebsite) {
		this.masterSupplierWebsite = masterSupplierWebsite;
	}

	public String getMasterSupplierFeedback() {
		return this.masterSupplierFeedback;
	}

	public void setMasterSupplierFeedback(String masterSupplierFeedback) {
		this.masterSupplierFeedback = masterSupplierFeedback;
	}

	public String getMasterSupplierAddfldChar1() {
		return this.masterSupplierAddfldChar1;
	}

	public void setMasterSupplierAddfldChar1(String masterSupplierAddfldChar1) {
		this.masterSupplierAddfldChar1 = masterSupplierAddfldChar1;
	}

	public String getMasterSupplierAddfldChar2() {
		return this.masterSupplierAddfldChar2;
	}

	public void setMasterSupplierAddfldChar2(String masterSupplierAddfldChar2) {
		this.masterSupplierAddfldChar2 = masterSupplierAddfldChar2;
	}

	public String getMasterSupplierAddfldChar3() {
		return this.masterSupplierAddfldChar3;
	}

	public void setMasterSupplierAddfldChar3(String masterSupplierAddfldChar3) {
		this.masterSupplierAddfldChar3 = masterSupplierAddfldChar3;
	}

	public Set getProdMobs() {
		return this.prodMobs;
	}

	public void setProdMobs(Set prodMobs) {
		this.prodMobs = prodMobs;
	}

	public Set getBillpaymentSuppliers() {
		return this.billpaymentSuppliers;
	}

	public void setBillpaymentSuppliers(Set billpaymentSuppliers) {
		this.billpaymentSuppliers = billpaymentSuppliers;
	}

}
