package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MasterCompBranch generated by hbm2java
 */
public class MasterCompBranch implements java.io.Serializable {

	private Integer masterCompBranchId;
	private MasterGenStatus masterGenStatus;
	private MasterCompany masterCompany;
	private MasterCompbranchCtgry masterCompbranchCtgry;
	private String masterCompBranchCode;
	private String masterCompBranchName;
	private String masterCompBranchAddress;
	private int masterCompBranchPerformace;
	private Date masterCompBranchStartdt;
	private Date masterCompBranchCloseddt;
	private String masterCompBranchAdfldChr1;
	private String masterCompBranchAdfldChr2;
	private String masterCompBranchAdfldChr3;
	private Set userRoles = new HashSet(0);

	public MasterCompBranch() {
	}

	public MasterCompBranch(MasterCompany masterCompany,
			MasterCompbranchCtgry masterCompbranchCtgry,
			String masterCompBranchCode, String masterCompBranchName,
			String masterCompBranchAddress, int masterCompBranchPerformace,
			Date masterCompBranchStartdt) {
		this.masterCompany = masterCompany;
		this.masterCompbranchCtgry = masterCompbranchCtgry;
		this.masterCompBranchCode = masterCompBranchCode;
		this.masterCompBranchName = masterCompBranchName;
		this.masterCompBranchAddress = masterCompBranchAddress;
		this.masterCompBranchPerformace = masterCompBranchPerformace;
		this.masterCompBranchStartdt = masterCompBranchStartdt;
	}

	public MasterCompBranch(MasterGenStatus masterGenStatus,
			MasterCompany masterCompany,
			MasterCompbranchCtgry masterCompbranchCtgry,
			String masterCompBranchCode, String masterCompBranchName,
			String masterCompBranchAddress, int masterCompBranchPerformace,
			Date masterCompBranchStartdt, Date masterCompBranchCloseddt,
			String masterCompBranchAdfldChr1, String masterCompBranchAdfldChr2,
			String masterCompBranchAdfldChr3, Set userRoles) {
		this.masterGenStatus = masterGenStatus;
		this.masterCompany = masterCompany;
		this.masterCompbranchCtgry = masterCompbranchCtgry;
		this.masterCompBranchCode = masterCompBranchCode;
		this.masterCompBranchName = masterCompBranchName;
		this.masterCompBranchAddress = masterCompBranchAddress;
		this.masterCompBranchPerformace = masterCompBranchPerformace;
		this.masterCompBranchStartdt = masterCompBranchStartdt;
		this.masterCompBranchCloseddt = masterCompBranchCloseddt;
		this.masterCompBranchAdfldChr1 = masterCompBranchAdfldChr1;
		this.masterCompBranchAdfldChr2 = masterCompBranchAdfldChr2;
		this.masterCompBranchAdfldChr3 = masterCompBranchAdfldChr3;
		this.userRoles = userRoles;
	}

	public Integer getMasterCompBranchId() {
		return this.masterCompBranchId;
	}

	public void setMasterCompBranchId(Integer masterCompBranchId) {
		this.masterCompBranchId = masterCompBranchId;
	}

	public MasterGenStatus getMasterGenStatus() {
		return this.masterGenStatus;
	}

	public void setMasterGenStatus(MasterGenStatus masterGenStatus) {
		this.masterGenStatus = masterGenStatus;
	}

	public MasterCompany getMasterCompany() {
		return this.masterCompany;
	}

	public void setMasterCompany(MasterCompany masterCompany) {
		this.masterCompany = masterCompany;
	}

	public MasterCompbranchCtgry getMasterCompbranchCtgry() {
		return this.masterCompbranchCtgry;
	}

	public void setMasterCompbranchCtgry(
			MasterCompbranchCtgry masterCompbranchCtgry) {
		this.masterCompbranchCtgry = masterCompbranchCtgry;
	}

	public String getMasterCompBranchCode() {
		return this.masterCompBranchCode;
	}

	public void setMasterCompBranchCode(String masterCompBranchCode) {
		this.masterCompBranchCode = masterCompBranchCode;
	}

	public String getMasterCompBranchName() {
		return this.masterCompBranchName;
	}

	public void setMasterCompBranchName(String masterCompBranchName) {
		this.masterCompBranchName = masterCompBranchName;
	}

	public String getMasterCompBranchAddress() {
		return this.masterCompBranchAddress;
	}

	public void setMasterCompBranchAddress(String masterCompBranchAddress) {
		this.masterCompBranchAddress = masterCompBranchAddress;
	}

	public int getMasterCompBranchPerformace() {
		return this.masterCompBranchPerformace;
	}

	public void setMasterCompBranchPerformace(int masterCompBranchPerformace) {
		this.masterCompBranchPerformace = masterCompBranchPerformace;
	}

	public Date getMasterCompBranchStartdt() {
		return this.masterCompBranchStartdt;
	}

	public void setMasterCompBranchStartdt(Date masterCompBranchStartdt) {
		this.masterCompBranchStartdt = masterCompBranchStartdt;
	}

	public Date getMasterCompBranchCloseddt() {
		return this.masterCompBranchCloseddt;
	}

	public void setMasterCompBranchCloseddt(Date masterCompBranchCloseddt) {
		this.masterCompBranchCloseddt = masterCompBranchCloseddt;
	}

	public String getMasterCompBranchAdfldChr1() {
		return this.masterCompBranchAdfldChr1;
	}

	public void setMasterCompBranchAdfldChr1(String masterCompBranchAdfldChr1) {
		this.masterCompBranchAdfldChr1 = masterCompBranchAdfldChr1;
	}

	public String getMasterCompBranchAdfldChr2() {
		return this.masterCompBranchAdfldChr2;
	}

	public void setMasterCompBranchAdfldChr2(String masterCompBranchAdfldChr2) {
		this.masterCompBranchAdfldChr2 = masterCompBranchAdfldChr2;
	}

	public String getMasterCompBranchAdfldChr3() {
		return this.masterCompBranchAdfldChr3;
	}

	public void setMasterCompBranchAdfldChr3(String masterCompBranchAdfldChr3) {
		this.masterCompBranchAdfldChr3 = masterCompBranchAdfldChr3;
	}

	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
