package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterCustRemdton generated by hbm2java
 */
public class MasterCustRemdton implements java.io.Serializable {

	private Integer masterCustRcmdId;
	private MasterGenStatus masterGenStatus;
	private String masterCustRcmdDesc;
	private Set masterCustomers = new HashSet(0);

	public MasterCustRemdton() {
	}

	public MasterCustRemdton(MasterGenStatus masterGenStatus,
			String masterCustRcmdDesc) {
		this.masterGenStatus = masterGenStatus;
		this.masterCustRcmdDesc = masterCustRcmdDesc;
	}

	public MasterCustRemdton(MasterGenStatus masterGenStatus,
			String masterCustRcmdDesc, Set masterCustomers) {
		this.masterGenStatus = masterGenStatus;
		this.masterCustRcmdDesc = masterCustRcmdDesc;
		this.masterCustomers = masterCustomers;
	}

	public Integer getMasterCustRcmdId() {
		return this.masterCustRcmdId;
	}

	public void setMasterCustRcmdId(Integer masterCustRcmdId) {
		this.masterCustRcmdId = masterCustRcmdId;
	}

	public MasterGenStatus getMasterGenStatus() {
		return this.masterGenStatus;
	}

	public void setMasterGenStatus(MasterGenStatus masterGenStatus) {
		this.masterGenStatus = masterGenStatus;
	}

	public String getMasterCustRcmdDesc() {
		return this.masterCustRcmdDesc;
	}

	public void setMasterCustRcmdDesc(String masterCustRcmdDesc) {
		this.masterCustRcmdDesc = masterCustRcmdDesc;
	}

	public Set getMasterCustomers() {
		return this.masterCustomers;
	}

	public void setMasterCustomers(Set masterCustomers) {
		this.masterCustomers = masterCustomers;
	}

}
