package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MasterCompany generated by hbm2java
 */
public class MasterCompany implements java.io.Serializable {

	private Integer companyId;
	private MasterGenStatus masterGenStatus;
	private String companyName;
	private String companyTin;
	private String companyAddress;
	private String comapnyLickey;
	private Integer companyAddfldNbr1;
	private Integer companyAddfldNbr2;
	private String companyAddfldChar1;
	private String companyAddfldChar2;
	private String companyAddfldChar3;
	private Set masterCompBranchs = new HashSet(0);

	public MasterCompany() {
	}

	public MasterCompany(MasterGenStatus masterGenStatus, String companyName,
			String companyTin, String companyAddress, String comapnyLickey) {
		this.masterGenStatus = masterGenStatus;
		this.companyName = companyName;
		this.companyTin = companyTin;
		this.companyAddress = companyAddress;
		this.comapnyLickey = comapnyLickey;
	}

	public MasterCompany(MasterGenStatus masterGenStatus, String companyName,
			String companyTin, String companyAddress, String comapnyLickey,
			Integer companyAddfldNbr1, Integer companyAddfldNbr2,
			String companyAddfldChar1, String companyAddfldChar2,
			String companyAddfldChar3, Set masterCompBranchs) {
		this.masterGenStatus = masterGenStatus;
		this.companyName = companyName;
		this.companyTin = companyTin;
		this.companyAddress = companyAddress;
		this.comapnyLickey = comapnyLickey;
		this.companyAddfldNbr1 = companyAddfldNbr1;
		this.companyAddfldNbr2 = companyAddfldNbr2;
		this.companyAddfldChar1 = companyAddfldChar1;
		this.companyAddfldChar2 = companyAddfldChar2;
		this.companyAddfldChar3 = companyAddfldChar3;
		this.masterCompBranchs = masterCompBranchs;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public MasterGenStatus getMasterGenStatus() {
		return this.masterGenStatus;
	}

	public void setMasterGenStatus(MasterGenStatus masterGenStatus) {
		this.masterGenStatus = masterGenStatus;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyTin() {
		return this.companyTin;
	}

	public void setCompanyTin(String companyTin) {
		this.companyTin = companyTin;
	}

	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	public String getComapnyLickey() {
		return this.comapnyLickey;
	}

	public void setComapnyLickey(String comapnyLickey) {
		this.comapnyLickey = comapnyLickey;
	}

	public Integer getCompanyAddfldNbr1() {
		return this.companyAddfldNbr1;
	}

	public void setCompanyAddfldNbr1(Integer companyAddfldNbr1) {
		this.companyAddfldNbr1 = companyAddfldNbr1;
	}

	public Integer getCompanyAddfldNbr2() {
		return this.companyAddfldNbr2;
	}

	public void setCompanyAddfldNbr2(Integer companyAddfldNbr2) {
		this.companyAddfldNbr2 = companyAddfldNbr2;
	}

	public String getCompanyAddfldChar1() {
		return this.companyAddfldChar1;
	}

	public void setCompanyAddfldChar1(String companyAddfldChar1) {
		this.companyAddfldChar1 = companyAddfldChar1;
	}

	public String getCompanyAddfldChar2() {
		return this.companyAddfldChar2;
	}

	public void setCompanyAddfldChar2(String companyAddfldChar2) {
		this.companyAddfldChar2 = companyAddfldChar2;
	}

	public String getCompanyAddfldChar3() {
		return this.companyAddfldChar3;
	}

	public void setCompanyAddfldChar3(String companyAddfldChar3) {
		this.companyAddfldChar3 = companyAddfldChar3;
	}

	public Set getMasterCompBranchs() {
		return this.masterCompBranchs;
	}

	public void setMasterCompBranchs(Set masterCompBranchs) {
		this.masterCompBranchs = masterCompBranchs;
	}

}
