package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;

/**
 * ProdMobAddinfo generated by hbm2java
 */
public class ProdMobAddinfo implements java.io.Serializable {

	private int prodMobAddinfoId;
	private ProdMob prodMob;
	private BigDecimal prodMobMrp;
	private BigDecimal prodMobDp;
	private BigDecimal prodMobSchemeamt;
	private BigDecimal prodMobBuyprice;
	private BigDecimal prodMobSellprice;
	private BigDecimal prodMobTaxamt;

	public ProdMobAddinfo() {
	}

	public ProdMobAddinfo(ProdMob prodMob) {
		this.prodMob = prodMob;
	}

	public ProdMobAddinfo(ProdMob prodMob, BigDecimal prodMobMrp,
			BigDecimal prodMobDp, BigDecimal prodMobSchemeamt,
			BigDecimal prodMobBuyprice, BigDecimal prodMobSellprice,
			BigDecimal prodMobTaxamt) {
		this.prodMob = prodMob;
		this.prodMobMrp = prodMobMrp;
		this.prodMobDp = prodMobDp;
		this.prodMobSchemeamt = prodMobSchemeamt;
		this.prodMobBuyprice = prodMobBuyprice;
		this.prodMobSellprice = prodMobSellprice;
		this.prodMobTaxamt = prodMobTaxamt;
	}

	public int getProdMobAddinfoId() {
		return this.prodMobAddinfoId;
	}

	public void setProdMobAddinfoId(int prodMobAddinfoId) {
		this.prodMobAddinfoId = prodMobAddinfoId;
	}

	public ProdMob getProdMob() {
		return this.prodMob;
	}

	public void setProdMob(ProdMob prodMob) {
		this.prodMob = prodMob;
	}

	public BigDecimal getProdMobMrp() {
		return this.prodMobMrp;
	}

	public void setProdMobMrp(BigDecimal prodMobMrp) {
		this.prodMobMrp = prodMobMrp;
	}

	public BigDecimal getProdMobDp() {
		return this.prodMobDp;
	}

	public void setProdMobDp(BigDecimal prodMobDp) {
		this.prodMobDp = prodMobDp;
	}

	public BigDecimal getProdMobSchemeamt() {
		return this.prodMobSchemeamt;
	}

	public void setProdMobSchemeamt(BigDecimal prodMobSchemeamt) {
		this.prodMobSchemeamt = prodMobSchemeamt;
	}

	public BigDecimal getProdMobBuyprice() {
		return this.prodMobBuyprice;
	}

	public void setProdMobBuyprice(BigDecimal prodMobBuyprice) {
		this.prodMobBuyprice = prodMobBuyprice;
	}

	public BigDecimal getProdMobSellprice() {
		return this.prodMobSellprice;
	}

	public void setProdMobSellprice(BigDecimal prodMobSellprice) {
		this.prodMobSellprice = prodMobSellprice;
	}

	public BigDecimal getProdMobTaxamt() {
		return this.prodMobTaxamt;
	}

	public void setProdMobTaxamt(BigDecimal prodMobTaxamt) {
		this.prodMobTaxamt = prodMobTaxamt;
	}

}
