package com.rainbow.billing.mbilling.common.domain;

// default package
// Generated Jul 4, 2014 8:21:11 PM by Hibernate Tools 3.3.0.GA

/**
 * UserRoleId generated by hbm2java
 */
public class UserRoleId implements java.io.Serializable {

	private int userid;
	private int roleid;
	private int branchid;

	public UserRoleId() {
	}

	public UserRoleId(int userid, int roleid, int branchid) {
		this.userid = userid;
		this.roleid = roleid;
		this.branchid = branchid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getRoleid() {
		return this.roleid;
	}

	public void setRoleid(int roleid) {
		this.roleid = roleid;
	}

	public int getBranchid() {
		return this.branchid;
	}

	public void setBranchid(int branchid) {
		this.branchid = branchid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleId))
			return false;
		UserRoleId castOther = (UserRoleId) other;

		return (this.getUserid() == castOther.getUserid())
				&& (this.getRoleid() == castOther.getRoleid())
				&& (this.getBranchid() == castOther.getBranchid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getRoleid();
		result = 37 * result + this.getBranchid();
		return result;
	}

}
